// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2025 Michael Gardner, A Bit of Help, Inc.
// Package: version
// Description: Semantic version information for hybrid_lib_go

// Package version provides semantic version information for the hybrid_lib_go library.
// This package is auto-generated by the release process and should not be edited manually.
//
// Architecture Notes:
//   - EXPORTED package for library consumers to access version info
//   - Part of CROSS-CUTTING concerns (outside hexagonal layers)
//   - Auto-generated during release preparation
//   - Single source of truth for library version
//
// Usage:
//
//	import "github.com/abitofhelp/hybrid_lib_go/version"
//
//	fmt.Printf("Using hybrid_lib_go v%s\n", version.Version)
//	if version.IsStable() {
//	    // Production-ready version
//	}
package version

// Semantic version components.
// See https://semver.org for specification.
const (
	// Major version - incremented for incompatible API changes.
	Major = 1

	// Minor version - incremented for backwards-compatible functionality.
	Minor = 0

	// Patch version - incremented for backwards-compatible bug fixes.
	Patch = 0

	// Prerelease identifier (e.g., "alpha", "beta.1", "rc.2").
	// Empty string indicates a stable release.
	Prerelease = ""

	// Build metadata (e.g., "20250101", "git.abc1234").
	// Does not affect version precedence.
	Build = ""
)

// Version returns the full semantic version string.
// Format: MAJOR.MINOR.PATCH[-PRERELEASE][+BUILD]
const Version = "1.0.0"

// IsPrerelease returns true if this is a prerelease version.
func IsPrerelease() bool {
	return Prerelease != ""
}

// IsStable returns true if this is a stable (non-prerelease) version.
func IsStable() bool {
	return !IsPrerelease()
}
