// Package version provides version information for the library.
//
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
//
// This file is automatically generated from the release version by:
//
//	scripts/release/release.py (Go adapter)
//
// To update the version:
//  1. Run: python3 scripts/release/release.py prepare <version>
//  2. Rebuild the project
//
// Purpose:
//
//	Provides version constants for CLI --version flags and runtime queries.
//	Single source of truth for version information.
//
// Design Notes:
//   - Version follows Semantic Versioning 2.0.0 (semver.org)
//   - Pre-release identifiers: -dev, -alpha.N, -beta.N, -rc.N
//   - Build metadata: +build.N, +commit.HASH
package version

// Semantic version components
const (
	Major = 1
	Minor = 0
	Patch = 0
)

// Prerelease identifier (e.g., "dev", "alpha.1", "beta.2", "rc.1")
// Empty string for stable releases
const Prerelease = ""

// BuildMetadata (e.g., "build.123", "commit.abc123")
// Empty string if not specified
const BuildMetadata = ""

// Version is the full version string (e.g., "0.1.0-dev", "1.2.3")
const Version = "1.0.0"

// IsPrerelease returns true if this is a pre-release version
func IsPrerelease() bool { return Prerelease != "" }

// IsDevelopment returns true if this is a development version
func IsDevelopment() bool { return Prerelease == "dev" }

// IsStable returns true if this is a stable release
func IsStable() bool { return !IsPrerelease() }
